polyclinic/urls.py
from django.contrib import admin
from django.urls import path, include

from polyclinic import settings

urlpatterns = [
    path('admin_page/', admin.site.urls),
    path('', include('polyclinic_app.urls')),
    # api
    path('api/v1/', include('polyclinic_app.drf_urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

polyclinic_app/urls.py
from django.urls import path, include
from . import views


app_name = 'polyclinic_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('region/<slug:slug_url>/', views.CityView.as_view(), name='city'),
    path('polyclinic/<slug:slug_url>/', views.PolyclinicView.as_view(), name='polyclinic'),
    path('api_documentation/', views.APIView.as_view(), name='api'),
]

polyclinic_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Region(models.Model):
    """ Область """
    region = models.CharField(
        max_length=50,
        verbose_name='область',
    )
    slug = models.SlugField(
        max_length=50,
        verbose_name='url',
    )

    class Meta:
        verbose_name = 'область'
        verbose_name_plural = 'области'

    def __str__(self):
        return self.region


class City(models.Model):
    """ Город """
    city_name = models.CharField(
        max_length=50,
        verbose_name='город',
    )
    slug = models.SlugField(
        max_length=50,
        verbose_name='url',
        unique=True,
    )
    phone_code = models.CharField(
        max_length=10,
        verbose_name='телефонный код',
    )
    region = models.ForeignKey(
        Region,
        on_delete=models.CASCADE,
        verbose_name='область',
        related_name='cities',
    )

    class Meta:
        verbose_name = 'город'
        verbose_name_plural = 'города'

    def __str__(self):
        return self.city_name


class Polyclinic(models.Model):
    """ Поликлиника """
    name = models.CharField(
        max_length=100,
        verbose_name='навание',
    )
    address = models.CharField(
        max_length=100,
        verbose_name='адрес',
    )
    website = models.URLField(
        max_length=300,
        verbose_name='сайт',
        blank=True,
    )
    making_an_appointment = models.URLField(
        max_length=300,
        verbose_name='онлайн-запись',
    )
    city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
        verbose_name='город',
        related_name='polyclinics',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='пользователь',
    )

    class Meta:
        verbose_name = 'поликлиника'
        verbose_name_plural = 'поликлиники'

    def __str__(self):
        return self.name


class PhoneNumber(models.Model):
    """ Номер телефона """
    title = models.CharField(
        max_length=30,
        verbose_name='имя',
    )
    number = models.CharField(
        max_length=50,
        verbose_name='телефон',
    )
    polyclinic = models.ForeignKey(
        Polyclinic,
        on_delete=models.CASCADE,
        verbose_name='поликлиника',
        related_name='phone',
    )

    class Meta:
        verbose_name = 'телефон'
        verbose_name_plural = 'телефоны'

    def __str__(self):
        return self.title

polyclinic_app/views.py
from django.views.generic import ListView, TemplateView

from .models import Region, City, Polyclinic
from . import drf_urls
from polyclinic import urls, settings
from .utils import POSTMixin


class IndexView(POSTMixin, ListView):
    """ Главная страница """
    template_name = 'polyclinic_app/index.html'
    context_object_name = 'regions'
    queryset = Region.objects.values('region', 'slug')

    def get_context_data(self, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['title'] = 'Поликлиники Беларуси'
        return context

    def post(self, request, **kwargs):
        return super().post(request, object_list=self.queryset, **kwargs)


class CityView(POSTMixin, ListView):
    """ Страница выбора города """
    template_name = 'polyclinic_app/city.html'
    context_object_name = 'cities'

    def get_queryset(self):
        return (City.objects
                .filter(region__slug=self.kwargs['slug_url'])
                .values('city_name', 'slug'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        region = Region.objects.filter(slug=self.kwargs['slug_url']).values('region')
        context['title'] = region[0].get('region')
        return context

    def post(self, request, **kwargs):
        return super().post(request, object_list=self.get_queryset(), **kwargs)


class PolyclinicView(POSTMixin, ListView):
    """ Страница выбора поликлиники """
    template_name = 'polyclinic_app/polyclinic.html'
    context_object_name = 'polyclinics'

    def get_queryset(self):
        return Polyclinic.objects.filter(city__slug=self.kwargs['slug_url'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        city = City.objects.get(slug=self.kwargs['slug_url'])
        context['title'] = f'Поликлиники: {city.region}'
        context['phone_code'] = city.phone_code
        return context

    def post(self, request, **kwargs):
        return super().post(request, object_list=self.get_queryset(), **kwargs)


class APIView(POSTMixin, TemplateView):
    """ Страница документации API """
    template_name = 'polyclinic_app/api.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        host = self.request.get_host()
        main_url = (urls.urlpatterns[-2].pattern
                    if settings.DEBUG
                    else urls.urlpatterns[-1].pattern)
        context['title'] = 'Документация API'
        context['host'] = host
        context['main_url'] = main_url
        context['all_polyclinics_url'] = None
        context['one_polyclinic_url'] = None

        for link in drf_urls.urlpatterns:
            if link.name == 'all':
                context['all_polyclinics_url'] = str(link.pattern)
            elif link.name == 'one':
                context['one_polyclinic_url'] = str(link.pattern)[:-9]

        return context

    def post(self, request, **kwargs):
        return super().post(request, **kwargs)

polyclinic_app/templates/polyclinic_app/api.html
{% extends 'polyclinic_app/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'polyclinic_app/css/api.css' %}">
{% endblock style %}

{% block title %}
<title>{{ title }}</title>
{% endblock title %}

{% block content %}
<div class="content">
    <h1 class="main-title">Документация по <span class="api-span">API</span></h1>
    <div class="documentation">
        <h3 class="api-title">Получение списка всех оптек в разрезе городов и областей:</h3>
        <p class="api-url">{{host}}/{{main_url}}{{all_polyclinics_url}}</p>
        <h3 class="api-title">Получение отдельной оптеки:</h3>
        <p class="api-url">{{host}}/{{main_url}}{{one_polyclinic_url}}<span class="api-span">id</span>/</p>
        <img src="{% static 'polyclinic_app/images/api_id.jpg' %}" alt="api-img" class="api-img">
    </div>
</div>
{% endblock content %}

polyclinic_app/templates/polyclinic_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'polyclinic_app/images/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'polyclinic_app/css/style.css' %}">
    {% block style %}
    {% endblock style %}
    {% block title %}
    {% endblock title %}
</head> 
<body>
    <div class="wrapper">
        <header class="header">
            <a href="{% url 'polyclinic_app:index' %}" class="main-link" title="На главную"></a>
            <form action="" class="search-form" method="post">
                {% csrf_token %}
                {% if messages %}
                    {% for m in messages %}
                    <p class="error">{{ m }}</p>
                    {% endfor %}
                {% endif %}  
                <input type="text" name="city" class="input" placeholder="Введите название города" required>
                <button type="submit" class="submit">Найти</button>                
            </form>
        </header>
        <main class="main">
            {% block content %}
            {% endblock content %}
        </main>
        <footer class="footer">
            <div class="contact-me">
                <p class="f-text">Нет Вашей поликлиники?</p>
                <a href="mailto:d.bandysik@gmail.com" class="mail-link">Напишите мне</a>
            </div>
            <a href="{% url 'polyclinic_app:api' %}" class="api-link">API-документация</a>
        </footer>
    </div>
    {% block script %}
    {% endblock script %}
</body>
</html>

polyclinic_app/templates/polyclinic_app/city.html
{% extends 'polyclinic_app/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'polyclinic_app/css/regions-and-cities.css' %}">
{% endblock style %}

{% block title %}
<title>{{ title }}</title>
{% endblock title %}

{% block content %}
<div class="content">
    <h1 class="main-title">Выберите город</h1>
    <div class="regions-and-cities">
        {% for c in cities %}
            <a href="{% url 'polyclinic_app:polyclinic' c.slug %}" class="city-link">{{ c.city_name }}</a>
        {% endfor %}
    </div>    
</div>
{% endblock content %}

polyclinic_app/templates/polyclinic_app/index.html
{% extends 'polyclinic_app/base.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" href="{% static 'polyclinic_app/css/regions-and-cities.css' %}">
{% endblock style %}

{% block title %}
<title>{{ title }}</title>
{% endblock title %}

{% block content %}
<div class="content">
    <h2 class="info-title">Все поликлиники Беларуси на одном сайте</h2>
    <h1 class="main-title">Выберите область</h1>
    <div class="regions-and-cities">
        {% for r in regions %}
            <a href="{% url 'polyclinic_app:city' r.slug %}" class="region-link">{{ r.region }}</a>
        {% endfor %}
    </div>
</div>
{% endblock content %}

polyclinic_app/templates/polyclinic_app/polyclinic.html
{% extends 'polyclinic_app/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'polyclinic_app/css/polyclinic.css' %}">
{% endblock style %}

{% block title %}
<title>{{ title }}</title>
{% endblock title %}

{% block content %}
<div class="content">
    <h1 class="main-title">{{ title }}</h1>
    <div class="polyclinics">
        {% for p in polyclinics %}
            <div class="polyclinic">
                <h2 class="p-title">{{ p.name }}</h2>
                <p class="p-address">ул. {{ p.address }}</p>
                <div class="numbers">
                {% for number in p.phone.all %}
                <a href="tel:{{ phone_code }}{{ number.number }}" class="p-phone">{{ number.title }}: <span class="tel">{{ phone_code }} {{ number.number }}</span></a>
                {% endfor %}
                </div>
                <a href="{{ p.making_an_appointment }}" class="mp-link" target="_blank">Записаться на прием</a>                                             
                <a href="{{ p.website }}" class="p-url" target="_blank">официальный сайт</a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'polyclinic_app/js/block.js' %}"></script>
{% endblock script %}